"""Generate the DJ filter coefficient tables.

One pot sweeps a 4th-order Linkwitz-Riley isolator: low-pass on the left half,
high-pass on the right half, no resonance. Each half is a cascade of two
identical Butterworth sections (Q = 1/sqrt(2)), so one coefficient set per
cutoff is enough.

The runtime uses the TPT state-variable form (Zavalishin):

    g  = tan(pi * fc / fs)
    k  = 1 / Q = sqrt(2)
    a1 = 1 / (1 + g * (g + k))
    a2 = g * a1
    a3 = g * a2

Cutoffs are spaced exponentially between the bypass edge and the extreme of
each half. Only stdlib math is used, so the tables can be regenerated
anywhere with `make djfilter`.
"""

import math

SAMPLE_RATE = 24000
POINTS = 64
COEFF_SHIFT = 24  # Q24 coefficients; the filter state itself is Q16

# Low-pass: bypass edge -> fully closed. High-pass: bypass edge -> fully open.
LOWPASS_EDGE_HZ = 10000.0
LOWPASS_MIN_HZ = 60.0
HIGHPASS_EDGE_HZ = 30.0
HIGHPASS_MAX_HZ = 6000.0

Q = 1.0 / math.sqrt(2.0)


def coefficients(fc):
    g = math.tan(math.pi * fc / SAMPLE_RATE)
    k = 1.0 / Q
    a1 = 1.0 / (1.0 + g * (g + k))
    a2 = g * a1
    a3 = g * a2
    scale = 1 << COEFF_SHIFT
    return [int(round(a1 * scale)), int(round(a2 * scale)), int(round(a3 * scale))]


def sweep(from_hz, to_hz):
    """POINTS cutoffs, exponentially spaced, index 0 at the bypass edge."""
    rows = []
    for i in range(POINTS):
        t = i / (POINTS - 1)
        fc = from_hz * math.pow(to_hz / from_hz, t)
        rows.append((fc, coefficients(fc)))
    return rows


def emit(name, rows):
    print(f"static const int32_t {name}[PIKO_DJ_FILTER_POINTS][3] = {{")
    for fc, (a1, a2, a3) in rows:
        print(f"    {{{a1}, {a2}, {a3}}},  // {fc:.1f} Hz")
    print("};")
    print()


def main():
    print("// Generated by generate_djfilter.py. Do not edit.")
    print("#pragma once")
    print()
    print("#include <stdint.h>")
    print()
    print(f"#define PIKO_DJ_FILTER_POINTS {POINTS}")
    print(f"#define PIKO_DJ_FILTER_COEFF_SHIFT {COEFF_SHIFT}")
    print(f"#define PIKO_DJ_FILTER_SAMPLE_RATE {SAMPLE_RATE}")
    print()
    emit("kDjFilterLowpass", sweep(LOWPASS_EDGE_HZ, LOWPASS_MIN_HZ))
    emit("kDjFilterHighpass", sweep(HIGHPASS_EDGE_HZ, HIGHPASS_MAX_HZ))


if __name__ == "__main__":
    main()
