name: build

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout project
        uses: actions/checkout@v6.0.3

      - name: Set up Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.11"

      - name: Install Pico SDK dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential gcc wget tar clang-format

      - name: Checkout pico-sdk
        uses: actions/checkout@v6.0.3
        with:
          repository: raspberrypi/pico-sdk
          path: pico-sdk
          submodules: true
          ref: 2.1.1

      - name: Set PICO_SDK_PATH
        run: echo "PICO_SDK_PATH=$GITHUB_WORKSPACE/pico-sdk" >> $GITHUB_ENV

      - name: Build uf2
        run: make build
